version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "5e:b7:a8:8c:9b:16:ef:87:f4:6d:9a:11:5e:d8:da:10"
      - run:
          name: Github config
          command: |
            git config user.email "antonio.lopez.8523@gmail.com"
            git config user.name "elements72"
      - run:
          name: Deploy
          command: | 
            ssh-keyscan -H lucia.cs.unibo.it >> ~/.ssh/known_hosts
            scp CSS/* antonio.lopez2@lucia.cs.unibo.it:/home/web/site202118/html/public/css/
            scp JS/* antonio.lopez2@lucia.cs.unibo.it:/home/web/site202118/html/public/js/
            scp HTML/* antonio.lopez2@lucia.cs.unibo.it:/home/web/site202118/html/public/html/


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
